<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ?
  "--format progress features" :
  "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts =
  "#{rerun_opts} --format rerun --out rerun.txt --strict --tags ~@wip"
html_opts =
  "--format html --out log/cucumber.out.html"
%>
default: <%= std_opts %>
wip:     --tags @wip:10 --wip features
